#!/bin/bash

set -eo pipefail

algo=ecdsa
key_path="../chain/rgdd-$algo.key"
cert_path="../chain/rgdd-$algo.pem"
name="foobar-0.0.1"

if [[ ! -z $1 ]]; then
	name=$1
fi
echo "[Info] package name: $name" >&2


echo "[Info] generating StItem and signature..." >&2
pushd ../entry >/dev/null
	go run . --dir stitem --name $name
	openssl dgst -sha256 -sign $key_path -out stitem/$name.sig stitem/$name
	openssl base64 -A -in stitem/$name -out stitem/$name.b64
	openssl base64 -A -in stitem/$name.sig -out stitem/$name.sig.b64
	json=$(printf '{"item":"%s","signature":"%s","certificate":"%s"}'\
		$(cat stitem/$name.b64)\
		$(cat stitem/$name.sig.b64)\
		$(cat $cert_path |\
			sed '1,1d;$ d' |\
			xargs |\
			sed 's/ //g'))
	rm -f stitem/$name{,.sig,.b64,.sig.b64}
popd >/dev/null

echo "[Info] doing add-entry request"
curl --header "application/json" --request POST --data $json\
	localhost:6965/st/v1/add-entry
